### ISSUE TITLE
not exiting after task complete in some situations

### ISSUE THREAD

**Issue by trgill** [sid-project/sid#52]
Running a script to create a DM thin target invokes usid as expected.  But each time the script is run the number of sid processes running increases.

**Comment by prajnoha** [comment]
There's one important thing to keep in mind when considering worker process reuse! With the worker being forked, we also make a snapshot of the database kept in main process by implicitly sharing the memory with the parent in COW manner. Then workers are able to work with the consistent snapshot as a whole and not blocking the main database. Tthen, at the end of worker processing, the worker sends differences to the main process to merge it into the main database.

If we wanted to keep a pool of processes for recycling, we'd need some other way of  making a db snapshot. One way I was thinking of would be to use a memory allocation mechanism where we'd know exactly the region where all the database allocations are and so we could use `mmap` to map the memory region inside worker with `MAP_PRIVATE` flag to have the COW functionality. The memory region in the main process would be created via `shm_open` or `memfd_create` - something that could be shareable with the workers so they can map it...

**Comment by prajnoha** [comment]
> Running a script to create a DM thin target invokes usid as expected. But each time the script is run the number of sid processes running increases.

You mean that the workers never end and there are new and new being created? Currently, they should just exit if they have nothing else to do - currently, that right after they executed all the phases and exported the database (`_export_kv_store`).

**Comment by trgill** [comment]
> You mean that the workers never end and there are new and new being created? Currently, they should just exit if they have nothing else to do - currently, that right after they executed all the phases and exported the database (`_export_kv_store`).

Thanks for explaining how things should work!

Yes.  It looks like _on_worker_channel_event() is being triggered - but a subsequent error is preventing the process from exiting - so it is going back into the main loop.  I'm tracking it down now.

**Comment by trgill** [comment]
These are the log messages:

```
Jan 13 14:39:08 localhost.localdomain sid[73865]: <worker/596c3264-d181-4145-93cd-49c226ece31c> Custom message handling failed.
Jan 13 14:39:12 localhost.localdomain sid[73871]: <worker/3d81bf60-e3fa-447c-89aa-9bf4de758c45> Received command from worker proxy, but connection handle missing.

```

**Comment by prajnoha** [comment]
> These are the log messages:
> 
> ```
> Jan 13 14:39:08 localhost.localdomain sid[73865]: <worker/596c3264-d181-4145-93cd-49c226ece31c> Custom message handling failed.
> Jan 13 14:39:12 localhost.localdomain sid[73871]: <worker/3d81bf60-e3fa-447c-89aa-9bf4de758c45> Received command from worker proxy, but connection handle missing.
> ```

Hmm, so this comes from the https://github.com/sid-project/sid/blob/f64443e69f3a824ea1433debcf9ad98bebaeed3b/src/resource/ubridge.c#L3843

The `_worker_recv_fn` is a callback function called when we receive data on worker side on the "main process" ---> "worker" channel. This channel is currently used purely and only to send the connection FD (the client request from `usid` command). The part on SID's main process side that accepts new client connections is here

https://github.com/sid-project/sid/blob/f64443e69f3a824ea1433debcf9ad98bebaeed3b/src/resource/ubridge.c#L3920

On main SID process, we only accept the connection and send the accepted FD over to the worker to do the rest of the work (that's the part that starts with `_worker_recv_fn` on worker side). The `_worker_recv_fn` knows that there must be an FD - it's the only thing we expect from the main SID process. And if it's not there, we get those error messages printed.

So the question is why the FD is not there.

The exact check in `_worker_recv_fn` https://github.com/sid-project/sid/blob/f64443e69f3a824ea1433debcf9ad98bebaeed3b/src/resource/ubridge.c#L3845 checks if we have `data_spec->ext.used` - wherther we have extended part filled up. In case of the socket, the extended part can carry the FD.

**Comment by prajnoha** [comment]
I'd probably check the `worker_control_channel_send ` calls in main SID process (mainly the one that is called in https://github.com/sid-project/sid/blob/f64443e69f3a824ea1433debcf9ad98bebaeed3b/src/resource/ubridge.c#L3929 )

And whether the worker received this correctly.

**Comment by trgill** [comment]
On this line : 

https://github.com/sid-project/sid/blob/a64c0d55b7127cf7cc2306b836998ff5ef881390/src/resource/worker-control.c#L250

buf_data_size is 4 and  sizeof(*cmd) is also 4, so data_spec->data_size is set to 0.

**Comment by prajnoha** [comment]
> On this line in the child:
> 
> https://github.com/sid-project/sid/blob/a64c0d55b7127cf7cc2306b836998ff5ef881390/src/resource/worker-control.c#L250
> 
> buf_data_size is 4 and sizeof(*cmd) is also 4, so data_spec->data_size is set to 0.
> 
> looks like the parent is sending 0 length data - the data parameter to _on_ubridge_interface_event()
> 
> https://github.com/sid-project/sid/blob/a64c0d55b7127cf7cc2306b836998ff5ef881390/src/resource/ubridge.c#L3886
> 

That's OK, because parent (the main SID process) has no data to send right at that moment (in the future, if we need to support some other requests with possible data to send to the worker, we can also send data, but for now, we don't need that).

Right now, the main process just sends the FD of accepted connection for the worker to process it further. Sending the FD besides data is considered as "extended message" for the channel of type `WORKER_WIRE_SOCKET`  and we allow the data part of the message to be 0, while the extension is still used.

> Should a worker exit if this line is hit?
> 
> https://github.com/sid-project/sid/blob/a64c0d55b7127cf7cc2306b836998ff5ef881390/src/resource/worker-control.c#L355
> 

Good question! Well, it's a callback that is supposed to do some custom action on reception. So you're right, we should probably also fail/exit the whole worker. If everything was OK or if this was a problem that can be ignored, then the callback would just return success (and maybe just pust warnings in the log). But if the callback return error, then it probably doesn't make sense to continue further with worker processing.

**Comment by prajnoha** [comment]
> Right now, the main process just sends the FD of accepted connection for the worker to process it further. Sending the FD besides data is considered as "extended message" for the channel of type `WORKER_WIRE_SOCKET` and we allow the data part of the message to be 0, while the extension is still used.

(...we know that there's also the extension sent by the fact that there's `cmd == WORKER_CHANNEL_CMD_DATA_EXT`. If there was not extension used, it would be just WORKER_CHANNEL_CMD_DATA`)

**Comment by prajnoha** [comment]
> Should a worker exit if this line is hit?
> 
> https://github.com/sid-project/sid/blob/a64c0d55b7127cf7cc2306b836998ff5ef881390/src/resource/worker-control.c#L355

Hmm, interesting, i gave it a try and it looks like that this line is the cause:

https://github.com/sid-project/sid/blob/7ab9609a30e19357ea42c30af44a392ffb564e86/src/resource/worker-control.c#L696-L697

Not sure why yet...

**Comment by prajnoha** [comment]
Ah, it's possible that the resources are now stacked a bit differently than it was when I commented this line long ago :) So I suspect we're destroying wrong resource! Looking at the resource tree now at that point...

**Comment by prajnoha** [comment]
OK, I've found the culprit, there are actually two issues here (both introduced by later changes after I commented out the `sid_resource_destroy` call in `worker_control_get_new_worker`):

- One is that the connections on path between  `worker_control` and top-level `sid` resource got a bit stricter, so walking from the `worker_control` upwards actually stops at `ubridge` internal resource, not the `sid` resource and hence we do not destroy everything we need then (but this is not the issue causing the problem you observe).
  
- Another issue is caused by introduction of the `struct worker_channel` abstraction in worker-control code. More specifically, the channel specs are stored within `worker_control` resource (as `worker_control.channel_specs` array). When we create channels (`struct worker_channel`) based on the specs for both the `worker_proxy` resource (on parent side) and `worker` resource (on worker side), we simply reference the channel specs  stored in `worker_control` resource. That is OK for the `worker_proxy` which is always attached to the `worker_control` resource in main process. But this fails in `worker` resource because this one is alone/isolated, not attached to the `worker_control` resource (we don't need this one in the worker itself). And with the `sid_resource_destroy` call in the `worker_control_get_new_worker`, we also destroy the `worker_control` resource including those channels specs. And so we access freed memory (it's also visible in `valgrind` output).

Sounds complex, but I think it'll be more clearer from the patch... I'll patch this...

**Comment by prajnoha** [comment]
(...as a consequence the channel handling in worker doesn't work because we access freed memory, so this might as well SEGFAULT)

**Comment by trgill** [comment]
Thanks very much.  I'm still climbing the learning curve.  This would have been difficult for me to solve.

**Comment by prajnoha** [comment]
Should be resolved now with:

8d5be2921f990bbaa42441cbb43a41544200c5ee
3974a45210b2f1ab43eae99b182b424d94f24e0a
3476e57736a5a335336fdc63093a290606a401ee
6a4dbe254cb3689dd4130c53ba219006b3180c8f
